### ISSUE TITLE
Notify VRMS of Climate Collabathon Meeting Times

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#4] opened 2020-10-08 23:45 UTC
### Overview
VRMS (Volunteer Relationship Management System) needs to know details of weekly team meetings

### Action Items

- [ ] Notify VRMS of weekly team meetings once project card issue completed

**Comment by ExperimentsInHonesty** [comment] 2021-08-05 03:15
@PLoiya will follow up with David Rubinstein in the #vrms channel

**Comment by PLoiya** [comment] 2021-08-05 23:54
Dropped a note to David in the slack/VRMS channel. Awaiting for the response.

**Comment by drubgrubby** [comment] 2021-08-06 00:33
@PLoiya -> You do not have to be on the website to have your meeting times on VRMS.  

Just go to https://github.com/hackforla/VRMS/issues/new/choose and create a new ticket to add/edit meeting time. In that ticket, you can also let me know information about the project so I can set it up in the database. 

Let me know as much of this information as you have, and I'll set you up in the database and add the meeting times. 

name 
description
 githubIdentifier
 githubUrl
 slackUrl 
googleDriveUrl 
googleDriveId
 hflaWebsiteUrl 
videoConferenceLink

It doesn't have to be complete, all we really need is the project name to get the meeting times up and running, but if we add the information now you won't have to do it later.

**Comment by PLoiya** [comment] 2021-08-06 14:53
As advised by David, the issue is created - https://github.com/hackforla/VRMS/issues/658 on the same.

**Comment by PLoiya** [comment] 2021-08-12 02:34
Verified on the hackforla.ord so closing the issue.

**Closed by PLoiya** 2021-08-12 02:34 UTC
Labels: documentation, role: product management, Bucket: missing
